### ISSUE TITLE
Cargo build is to long

### ISSUE THREAD

**Issue by AdiCahyaSaputra** [KaiserY/ooxmlsdk#3]
I'm just trying to read pptx file using example code on [this example](https://github.com/KaiserY/ooxmlsdk/blob/main/examples/read_pptx/src/main.rs) but i just get this when i ran `cargo run`

![image](https://github.com/user-attachments/assets/db7fbc0c-dce6-4056-9f56-1490cf62d849)

for a very long time. This is my cargo.toml file

![image](https://github.com/user-attachments/assets/1f0d69c2-a865-47e5-8347-47caabb04d10)

if you want me to show more details that you need, just tell me please. I need help

**Comment by KaiserY** [comment]
I tried the example and it worked, it's just slow. This library generates tons of code and all types are statics (i.e. no generic or dynamic types), and rustc is just slow, so all together it's slow slow.

Recently I will try to split the library by features, like spliting `docx`, `xlsx` and `pptx`, and by office versions like `office2007`, `office2010` etc.

**Comment by AdiCahyaSaputra** [comment]
> I tried the example and it worked, it's just slow. This library generates tons of code and all types are statics (i.e. no generic or dynamic types), and rustc is just slow, so all together it's slow slow.
> 
> Recently I will try to split the library by features, like spliting `docx`, `xlsx` and `pptx`, and by office versions like `office2007`, `office2010` etc.

Yes it work but it's very slow on my machine. Splitting library by features seems like a great idea, i'll be wait for that 🔥
